version: "3.8"

services:
  backend:
    build:
      context: ./web
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./web:/app/app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3