version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./web:/app/app:ro
      - ./detector_output:/detector:ro
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  detector:
    build:
      context: ./detector
    container_name: detector
    restart: always
    volumes:
      - ./detector:/app:ro
      - ./best.pt:/app/best.pt:ro
      - ./detector_output:/output
    devices:
      - "/dev/video0:/dev/video0"
